{{- include "custos.validate" . -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "custos.fullname" . }}-config
  labels:
    {{- include "custos.labels" (dict "root" . "component" "config") | nindent 4 }}
data:
  config.yaml: |
    {{- include "custos.config" . | nindent 4 }}
