apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-custos
  labels:
    {{- include "custos.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: api
      port: {{ .Values.service.port }}
      targetPort: api
    - name: metrics
      port: {{ .Values.service.metricsPort }}
      targetPort: metrics
  selector:
    {{- include "custos.labels" . | nindent 4 }}
    app.kubernetes.io/component: serve
