# shellcheck shell=bash
# Custos node hooks - shared helpers (sourced by the prolog, epilog and
# namespace scripts; never executed directly). Generated by Custos; do not
# edit on the node.

PATH=/usr/sbin:/usr/bin:/sbin:/bin
export PATH
umask 077

CUSTOS_ETC=/etc/custos/node
CUSTOS_RUN=/run/custos
MOUNTS_TSV="$CUSTOS_ETC/mounts.tsv"

log() { logger -t custos-node -- "$*" || true; }
die() {
	log "ERROR: $*"
	exit 1
}

# meta_get <key>: value of a "meta" line in mounts.tsv.
meta_get() {
	local kind k v _rest
	while IFS=$'\t' read -r kind k v _rest; do
		if [ "$kind" = meta ] && [ "$k" = "$1" ]; then
			printf '%s' "$v"
			return 0
		fi
	done <"$MOUNTS_TSV"
	return 1
}

require_numeric() {
	case "$1" in
	'' | *[!0-9]*) return 1 ;;
	esac
	return 0
}

valid_account() {
	case "$1" in
	'' | *[!A-Za-z0-9._-]*) return 1 ;;
	esac
	[ "${#1}" -le 128 ]
}

# account_conflict <account>: success when the account maps to more than
# one tenant on this cluster (fail closed).
account_conflict() {
	local kind a _rest
	while IFS=$'\t' read -r kind a _rest; do
		if [ "$kind" = conflict ] && [ "$a" = "$1" ]; then
			return 0
		fi
	done <"$MOUNTS_TSV"
	return 1
}

# account_tenant <account>: tenant slug of the account, empty when unknown.
account_tenant() {
	local kind a t _rest
	while IFS=$'\t' read -r kind a t _rest; do
		if [ "$kind" = account ] && [ "$a" = "$1" ]; then
			printf '%s' "$t"
			return 0
		fi
	done <"$MOUNTS_TSV"
	return 0
}

# list_shared: "name fstype source target opts" per shared mount, parents first.
list_shared() {
	local kind name fstype source target opts _rest
	while IFS=$'\t' read -r kind name fstype source target opts _rest; do
		if [ "$kind" = shared ]; then
			printf '%s\t%s\t%s\t%s\t%s\n' "$name" "$fstype" "$source" "$target" "$opts"
		fi
	done <"$MOUNTS_TSV"
}

# list_tenant <account>: "name fstype source target opts" per tenant mount.
list_tenant() {
	local kind a t name fstype source target opts _rest
	while IFS=$'\t' read -r kind a t name fstype source target opts _rest; do
		if [ "$kind" = account ] && [ "$a" = "$1" ]; then
			printf '%s\t%s\t%s\t%s\t%s\n' "$name" "$fstype" "$source" "$target" "$opts"
		fi
	done <"$MOUNTS_TSV"
}

# list_tenant_by_slug <tenant>: tenant mounts, de-duplicated by target.
list_tenant_by_slug() {
	local kind a t name fstype source target opts _rest
	while IFS=$'\t' read -r kind a t name fstype source target opts _rest; do
		if [ "$kind" = account ] && [ "$t" = "$1" ]; then
			printf '%s\t%s\t%s\t%s\t%s\n' "$name" "$fstype" "$source" "$target" "$opts"
		fi
	done <"$MOUNTS_TSV" | sort -u
}

# host_mount <fstype> <source> <target> <opts> <timeout>
# Mount on the host unless already mounted from the same source. A target
# mounted from a different source fails closed (return 2).
host_mount() {
	local fstype=$1 source=$2 target=$3 opts=$4 tmo=$5 cur
	if mountpoint -q "$target"; then
		cur=$(findmnt -n -o SOURCE -M "$target" || true)
		if [ "$cur" = "$source" ]; then
			return 0
		fi
		log "ERROR: ISOLATION_VIOLATION target $target is mounted from a different source"
		return 2
	fi
	(umask 022 && mkdir -p -- "$target") || return 1
	timeout "$tmo" mount -t "$fstype" -o "$opts" "$source" "$target"
}

# host_umount <target> <timeout>: unmount with retry and lazy fallback,
# then verify. Success only when the target is no longer a mount point.
host_umount() {
	local target=$1 tmo=$2
	if ! mountpoint -q "$target"; then
		return 0
	fi
	timeout "$tmo" umount "$target" 2>/dev/null ||
		{ sleep 1; timeout "$tmo" umount "$target" 2>/dev/null; } ||
		umount -l "$target" 2>/dev/null || true
	if mountpoint -q "$target"; then
		log "ERROR: $target is still mounted after unmount attempts"
		return 1
	fi
	return 0
}

# job_account <jobid>: account recorded by the prolog ("-" when none).
job_account_from_file() {
	local f="$CUSTOS_RUN/jobs/$1/account"
	[ -r "$f" ] || return 1
	local a
	IFS= read -r a <"$f" || true
	printf '%s' "$a"
}
