AuthType=auth/slurm
AuthAltTypes=auth/jwt
AuthAltParameters=jwt_key=/etc/slurm/jwt_hs256.key
DbdHost=slurmdbd
DbdPort=6819
PidFile=/run/slurmdbd/dbd.pid
SlurmUser=slurm
StorageType=accounting_storage/mysql
StorageHost=mariadb
StoragePort=3306
StorageUser=slurm
StoragePass=MExT0Qms12cKhc4cGcJnjPpABtGCVe9XiYGXdGbpX3s
StorageLoc=slurm_acct_db
