#!/bin/bash
# Custos node epilog: release tenant mounts when the last job of the tenant
# ends (host isolation modes) and clean per-job state. Generated by
# Custos; do not edit on the node.
set -euo pipefail
# shellcheck source=lib/common.sh
. /etc/custos/node/lib/common.sh

jobid=${SLURM_JOB_ID:-}
require_numeric "$jobid" || die "SLURM_JOB_ID missing or not numeric"

mkdir -p "$CUSTOS_RUN" "$CUSTOS_RUN/jobs" "$CUSTOS_RUN/active"
exec 9>"$CUSTOS_RUN/mounts.lock"
flock 9

mode=$(meta_get mode) || die "mounts.tsv has no mode"
tmo=$(meta_get timeout) || die "mounts.tsv has no timeout"
require_numeric "$tmo" || die "invalid mount timeout"

jobdir="$CUSTOS_RUN/jobs/$jobid"

if [ "$mode" = namespace ]; then
	# The namespace teardown drops the mounts (ns-epilog.sh unmounted them);
	# shared mounts are never unmounted.
	rm -rf -- "$jobdir"
	exit 0
fi

tenant=
if [ -r "$jobdir/tenant" ]; then
	IFS= read -r tenant <"$jobdir/tenant" || true
fi

if [ -z "$tenant" ]; then
	rm -rf -- "$jobdir"
	exit 0
fi

rm -f -- "$CUSTOS_RUN/active/$tenant/$jobid"

remaining=0
for m in "$CUSTOS_RUN/active/$tenant"/*; do
	if [ -e "$m" ]; then
		remaining=1
		break
	fi
done

if [ "$remaining" -eq 0 ]; then
	failed=0
	# Reverse target order so nested mounts go first.
	while IFS=$'\t' read -r _name _fstype _source target _opts; do
		host_umount "$target" "$tmo" || failed=1
	done < <(list_tenant_by_slug "$tenant" | sort -t "$(printf '\t')" -k4,4 -r)
	if [ "$failed" -ne 0 ]; then
		die "tenant $tenant mounts still present after epilog; failing so the node drains"
	fi
	rmdir -- "$CUSTOS_RUN/active/$tenant" 2>/dev/null || true
fi

rm -rf -- "$jobdir"
exit 0
