#!/bin/bash
# Custos namespace clone script (namespace/linux clone_ns_script): mounts
# the tenant shares of the job's account inside the job's private mount
# namespace. Generated by Custos; do not edit on the node.
set -euo pipefail
# shellcheck source=lib/common.sh
. /etc/custos/node/lib/common.sh

ns=${SLURM_NS:-}
case "$ns" in
/*) ;;
*) die "SLURM_NS missing or not an absolute path" ;;
esac

account=${SLURM_JOB_ACCOUNT:-}
if [ -z "$account" ]; then
	jobid=${SLURM_JOB_ID:-}
	require_numeric "$jobid" || die "cannot resolve job account: SLURM_JOB_ACCOUNT and SLURM_JOB_ID unavailable; failing closed"
	account=$(job_account_from_file "$jobid") || die "cannot resolve job account: no $CUSTOS_RUN/jobs/$jobid/account; failing closed"
fi
if [ "$account" = - ]; then
	exit 0
fi
valid_account "$account" || die "invalid job account; failing closed"

tmo=$(meta_get timeout) || die "mounts.tsv has no timeout"
require_numeric "$tmo" || die "invalid mount timeout"

if account_conflict "$account"; then
	die "ISOLATION_VIOLATION account $account maps to more than one tenant"
fi

while IFS=$'\t' read -r name fstype source target opts; do
	if nsenter --mount="$ns" -- mountpoint -q "$target"; then
		cur=$(nsenter --mount="$ns" -- findmnt -n -o SOURCE -M "$target" || true)
		if [ "$cur" = "$source" ]; then
			continue
		fi
		die "ISOLATION_VIOLATION $target already mounted from a different source in the job namespace"
	fi
	(umask 022 && nsenter --mount="$ns" -- mkdir -p -- "$target") || die "mkdir $target failed in namespace"
	nsenter --mount="$ns" -- timeout "$tmo" mount -t "$fstype" -o "$opts" "$source" "$target" ||
		die "tenant mount $name failed in namespace"
done < <(list_tenant "$account")
exit 0
