#!/bin/bash
# Custos namespace epilog (namespace/linux clone_ns_epilog): unmounts the
# tenant shares inside the job's mount namespace before it is torn down.
# Generated by Custos; do not edit on the node.
set -euo pipefail
# shellcheck source=lib/common.sh
. /etc/custos/node/lib/common.sh

ns=${SLURM_NS:-}
case "$ns" in
/*) ;;
*) die "SLURM_NS missing or not an absolute path" ;;
esac

account=${SLURM_JOB_ACCOUNT:-}
if [ -z "$account" ]; then
	jobid=${SLURM_JOB_ID:-}
	require_numeric "$jobid" || die "cannot resolve job account: SLURM_JOB_ACCOUNT and SLURM_JOB_ID unavailable"
	account=$(job_account_from_file "$jobid") || die "cannot resolve job account: no $CUSTOS_RUN/jobs/$jobid/account"
fi
if [ "$account" = - ]; then
	exit 0
fi
valid_account "$account" || die "invalid job account"

tmo=$(meta_get timeout) || die "mounts.tsv has no timeout"
require_numeric "$tmo" || die "invalid mount timeout"

while IFS=$'\t' read -r _name _fstype _source target _opts; do
	if ! nsenter --mount="$ns" -- mountpoint -q "$target"; then
		continue
	fi
	nsenter --mount="$ns" -- timeout "$tmo" umount "$target" 2>/dev/null ||
		nsenter --mount="$ns" -- umount -l "$target" 2>/dev/null || true
done < <(list_tenant "$account" | sort -t "$(printf '\t')" -k4,4 -r)
exit 0
