#!/bin/bash
# Custos node prolog: shared mounts, tenant mount isolation bookkeeping.
# Generated by Custos; do not edit on the node.
set -euo pipefail
# shellcheck source=lib/common.sh
. /etc/custos/node/lib/common.sh

jobid=${SLURM_JOB_ID:-}
require_numeric "$jobid" || die "SLURM_JOB_ID missing or not numeric"

mkdir -p "$CUSTOS_RUN" "$CUSTOS_RUN/jobs" "$CUSTOS_RUN/active"
exec 9>"$CUSTOS_RUN/mounts.lock"
flock 9

mode=$(meta_get mode) || die "mounts.tsv has no mode"
tmo=$(meta_get timeout) || die "mounts.tsv has no timeout"
require_numeric "$tmo" || die "invalid mount timeout"

# Shared mounts: every mode, every job.
while IFS=$'\t' read -r name fstype source target opts; do
	rc=0
	host_mount "$fstype" "$source" "$target" "$opts" "$tmo" || rc=$?
	if [ "$rc" -ne 0 ]; then
		die "shared mount $name failed (rc=$rc)"
	fi
done < <(list_shared)

account=${SLURM_JOB_ACCOUNT:-}
tenant=
if valid_account "$account"; then
	if account_conflict "$account"; then
		die "ISOLATION_VIOLATION account $account maps to more than one tenant"
	fi
	tenant=$(account_tenant "$account")
else
	account=-
fi

jobdir="$CUSTOS_RUN/jobs/$jobid"
mkdir -p "$jobdir"
printf '%s\n' "$account" >"$jobdir/account"
printf '%s\n' "$tenant" >"$jobdir/tenant"

case "$mode" in
namespace | tenant_exclusive | node_exclusive) ;;
*) die "unknown isolation mode $mode" ;;
esac

# Unknown accounts (non-Custos jobs) get only the shared mounts; in
# namespace mode tenant shares are mounted by ns-clone.sh, not here.
if [ -z "$tenant" ] || [ "$mode" = namespace ]; then
	exit 0
fi
marker_tenant=$tenant

# Another tenant (any job for node_exclusive) already present: refuse.
for d in "$CUSTOS_RUN"/active/*; do
	[ -d "$d" ] || continue
	other=${d##*/}
	for m in "$d"/*; do
		[ -e "$m" ] || continue
		if [ "$m" = "$d/$jobid" ]; then
			continue
		fi
		if [ "$mode" = node_exclusive ] || [ "$other" != "$marker_tenant" ]; then
			rm -rf -- "$jobdir"
			die "ISOLATION_VIOLATION job $jobid ($marker_tenant) conflicts with active job ${m##*/} of $other"
		fi
	done
done

mkdir -p "$CUSTOS_RUN/active/$marker_tenant"
: >"$CUSTOS_RUN/active/$marker_tenant/$jobid"

# abort_tenant_mounts: undo a failed attempt. Drop this job's marker and, when
# no other job of the tenant remains, unmount every tenant target (reverse
# order) so a half-mounted tenant is never left behind. Fail closed.
abort_tenant_mounts() {
	rm -f -- "$CUSTOS_RUN/active/$marker_tenant/$jobid"
	rm -rf -- "$jobdir"
	local m
	for m in "$CUSTOS_RUN/active/$marker_tenant"/*; do
		if [ -e "$m" ]; then
			return 0
		fi
	done
	local t src cur
	while IFS=$'\t' read -r _name _fstype src t _opts; do
		# Only release what this tenant mounted; never touch a foreign mount.
		cur=$(findmnt -n -o SOURCE -M "$t" || true)
		if [ "$cur" = "$src" ]; then
			host_umount "$t" "$tmo" || true
		fi
	done < <(list_tenant_by_slug "$marker_tenant" | sort -t "$(printf '\t')" -k4,4 -r)
	rmdir -- "$CUSTOS_RUN/active/$marker_tenant" 2>/dev/null || true
}

while IFS=$'\t' read -r name fstype source target opts; do
	rc=0
	host_mount "$fstype" "$source" "$target" "$opts" "$tmo" || rc=$?
	if [ "$rc" -ne 0 ]; then
		abort_tenant_mounts
		die "tenant mount $name failed (rc=$rc)"
	fi
done < <(list_tenant "$account")
exit 0
