version: "1"
name: exonical/custos-validator
labels:
  org.opencontainers.image.title: custos-validator
  org.opencontainers.image.description: Custos script validation sidecar
  org.opencontainers.image.vendor: Exonical
maintainers:
  - name: Exonical Platform Team
    email: platform@exonical.invalid
tags:
  - latest
args: {}
resources: []
container:
  user: "65532"
  expose: [8481]
