// Package envcheck classifies and validates user-requested environment
// variables for job submission (docs/script-validation.md §Environment).
package envcheck

import (
	"context"
	"regexp"
	"strings"

	"github.com/Exonical/custos/internal/validation"
	"github.com/Exonical/custos/internal/workflowspec"
)

// Class of an environment variable.
type Class string

// Environment variable classes.
const (
	ClassControlled Class = "controlled" // set by Custos/Slurm; user values rejected
	ClassGenerated  Class = "generated"  // produced by ResolvedSoftware
	ClassFiltered   Class = "filtered"   // default-denied; tenant policy may allow
	ClassUser       Class = "user"       // user-configurable
)

// EnvPolicy carries the resolved policy bits envcheck needs.
type EnvPolicy struct {
	AllowFiltered  []string // filtered names a tenant explicitly allows
	GeneratedNames []string // names produced by ResolvedSoftware
}

var (
	controlledExact = map[string]bool{
		"PATH": true, "HOME": true, "USER": true, "TMPDIR": true,
	}
	controlledGlobs = []string{"CUSTOS_", "SLURM_", "SBATCH_", "SRUN_", "SALLOC_"}

	filteredExact = map[string]bool{
		"LD_PRELOAD": true, "LD_AUDIT": true, "LD_LIBRARY_PATH": true,
		"GLIBC_TUNABLES": true, "BASH_ENV": true, "ENV": true,
		"PROMPT_COMMAND": true, "SHELLOPTS": true,
		"PYTHONSTARTUP": true, "PYTHONHOME": true, "PERL5OPT": true,
		"RUBYOPT": true, "NODE_OPTIONS": true, "JAVA_TOOL_OPTIONS": true,
		"CUDA_VISIBLE_DEVICES": true, "ROCR_VISIBLE_DEVICES": true,
	}
	filteredGlobs = []string{"LD_DEBUG", "OMPI_", "PMIX_", "I_MPI_", "UCX_", "NCCL_"}
)

var nameRe = regexp.MustCompile(`^[A-Za-z_][A-Za-z0-9_]*$`)

// Classify returns the class of an environment variable name.
func Classify(name string, generated []string) Class {
	upper := strings.ToUpper(name)
	for _, g := range controlledGlobs {
		if strings.HasPrefix(upper, g) {
			return ClassControlled
		}
	}
	if controlledExact[name] {
		return ClassControlled
	}
	for _, g := range generated {
		if name == g {
			return ClassGenerated
		}
	}
	if filteredExact[name] {
		return ClassFiltered
	}
	for _, g := range filteredGlobs {
		if strings.HasPrefix(name, g) {
			return ClassFiltered
		}
	}
	// *_PROXY / *_proxy case-insensitive.
	if strings.HasSuffix(upper, "_PROXY") {
		return ClassFiltered
	}
	return ClassUser
}

// caseVariantOfFiltered reports whether name is a case variant of a
// filtered or controlled name (env names are case-sensitive on Linux,
// but a lowercase LD_PRELOAD is almost certainly a mistake).
func caseVariantOfFiltered(name string) bool {
	upper := strings.ToUpper(name)
	if upper == name {
		return false
	}
	return Classify(upper, nil) != ClassUser
}

// Validate checks user-requested environment variables. Codes:
// CUSTOS301 controlled, CUSTOS302 generated, CUSTOS303 filtered,
// CUSTOS304 invalid name/value, CUSTOS305 case-variant warning.
func Validate(env map[string]string, pol EnvPolicy) []validation.Diagnostic {
	var out []validation.Diagnostic
	allowed := make(map[string]bool, len(pol.AllowFiltered))
	for _, n := range pol.AllowFiltered {
		allowed[n] = true
	}
	total := 0
	for name, val := range env {
		d := validation.Diagnostic{Source: "envcheck"}
		class := Classify(name, pol.GeneratedNames)
		switch {
		case !nameRe.MatchString(name) || len(name) > 128:
			out = append(out, diag(d, "CUSTOS304", validation.SeverityError,
				"invalid environment variable name "+name))
			continue
		case len(val) > 32*1024:
			out = append(out, diag(d, "CUSTOS304", validation.SeverityError,
				name+" exceeds the 32 KiB value limit"))
		case strings.ContainsAny(val, "\x00\r\n"):
			out = append(out, diag(d, "CUSTOS304", validation.SeverityError,
				name+" contains NUL/CR/LF characters"))
		}
		switch class {
		case ClassControlled:
			out = append(out, diag(d, "CUSTOS301", validation.SeverityError,
				name+" is controlled by Custos/Slurm and cannot be preset"))
		case ClassGenerated:
			out = append(out, diag(d, "CUSTOS302", validation.SeverityError,
				name+" is generated by the software environment and cannot be overridden"))
		case ClassFiltered:
			if !allowed[name] {
				out = append(out, diag(d, "CUSTOS303", validation.SeverityError,
					name+" is filtered by policy"))
			}
		case ClassUser:
			if caseVariantOfFiltered(name) {
				out = append(out, diag(d, "CUSTOS305", validation.SeverityWarning,
					name+" is a case variant of a filtered variable"))
			}
		}
		total += len(name) + len(val) + 1
	}
	if total > 256*1024 {
		out = append(out, validation.Diagnostic{
			Source: "envcheck", Code: "CUSTOS304",
			Severity: validation.SeverityError,
			Message:  "environment exceeds the 256 KiB total limit",
		})
	}
	validation.SortDiagnostics(out)
	return out
}

func diag(d validation.Diagnostic, code string, sev validation.Severity, msg string) validation.Diagnostic {
	d.Code, d.Severity, d.Message = code, sev, msg
	return d
}

// Validator adapts Validate to the pipeline's ScriptValidator port so
// the pipeline is the single place that produces diagnostics. The
// effective policy's FilteredEnvAllowed list is read per-request from
// the input.
type Validator struct{}

// Name returns the validator source name.
func (Validator) Name() string { return "envcheck" }

// Languages returns nil — env check applies to every language.
func (Validator) Languages() []workflowspec.Language { return nil }

// Validate checks Input.Environment against the configured policy.
func (v Validator) Validate(ctx context.Context, in validation.Input) (validation.Result, error) {
	res := validation.Result{Tool: validation.ToolVersion{Name: "envcheck", Version: "v1"}}
	if err := ctx.Err(); err != nil {
		return res, err
	}
	res.Diagnostics = Validate(in.Environment,
		EnvPolicy{AllowFiltered: in.Policy.FilteredEnvAllowed})
	return res, nil
}
