/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * This interface was referenced by `CustosWorkflow`'s JSON-Schema
 * via the `definition` "scriptRef".
 */
export type ScriptRef =
  | string
  | ({
      [k: string]: unknown;
    } & {
      ref?: string;
      language?: "bash" | "sh" | "python" | "yaml" | "json";
      inline?: string;
    });

export interface CustosWorkflow {
  apiVersion: "custos.io/v1alpha1";
  kind: "Workflow";
  metadata: {
    name: string;
    labels?: {
      [k: string]: string;
    };
  };
  spec: {
    parameters?: {
      [k: string]: Parameter;
    };
    placement?: Placement;
    defaults?: Defaults;
    secrets?: {
      [k: string]: SecretUse;
    };
    execution?: Execution;
    /**
     * @minItems 1
     */
    tasks: [Task, ...Task[]];
  };
}
/**
 * This interface was referenced by `CustosWorkflow`'s JSON-Schema
 * via the `definition` "parameter".
 */
export interface Parameter {
  type: "string" | "integer" | "boolean";
  required?: boolean;
  default?: unknown;
  pattern?: string;
  minimum?: number;
  maximum?: number;
  enum?: unknown[];
}
/**
 * This interface was referenced by `CustosWorkflow`'s JSON-Schema
 * via the `definition` "placement".
 */
export interface Placement {
  cluster?: string;
  requirements?: {
    [k: string]: unknown;
  };
}
/**
 * This interface was referenced by `CustosWorkflow`'s JSON-Schema
 * via the `definition` "defaults".
 */
export interface Defaults {
  account?: string | null;
  partition?: string;
  qos?: string;
  workingDirectory?: string;
  env?:
    | {
        [k: string]: string;
      }
    | string[];
}
/**
 * This interface was referenced by `CustosWorkflow`'s JSON-Schema
 * via the `definition` "secretUse".
 */
export interface SecretUse {
  ref: string;
  use: "env" | "wrapped_token";
  envName?: string;
}
/**
 * This interface was referenced by `CustosWorkflow`'s JSON-Schema
 * via the `definition` "execution".
 */
export interface Execution {
  strategy?: "auto" | "engine" | "native";
  failurePolicy?: "fail" | "continue";
}
/**
 * This interface was referenced by `CustosWorkflow`'s JSON-Schema
 * via the `definition` "task".
 */
export interface Task {
  name: string;
  /**
   * @deprecated
   * Deprecated compatibility aliases. New specs should omit type except for shell and condition; use launch to choose sbatch or srun.
   */
  type?: "batch" | "mpi" | "gpu" | "array" | "shell" | "stageIn" | "stageOut" | "interactive" | "condition";
  /**
   * Slurm launch model; defaults to sbatch, except legacy type mpi defaults to srun.
   */
  launch?: "sbatch" | "srun";
  dependsOn?: string[];
  onDependencyFailure?: "fail" | "run";
  when?: string;
  fanOut?: FanOut;
  resources?: TaskResources;
  placement?: Placement;
  image?: Image;
  multinode?: Multinode;
  command?: string[];
  script?: ScriptRef;
  args?: string[];
  env?:
    | {
        [k: string]: string;
      }
    | string[];
  software?: SoftwareRequirement[];
  outputs?: {
    [k: string]: Output;
  };
  retry?: Retry;
  array?: ArraySpec;
  partition?: string;
  qos?: string;
  workingDirectory?: string;
  stdout?: string;
  stderr?: string;
}
/**
 * This interface was referenced by `CustosWorkflow`'s JSON-Schema
 * via the `definition` "fanOut".
 */
export interface FanOut {
  count?: number | string;
  from?: string;
}
/**
 * This interface was referenced by `CustosWorkflow`'s JSON-Schema
 * via the `definition` "taskResources".
 */
export interface TaskResources {
  cpu?: number;
  cpuAffinity?: "none" | "core" | "socket" | "numa";
  memory?: string;
  walltime?: string;
  gpu?: GpuRequest;
  nodes?: number;
  tasks?: number;
  tasksPerNode?: number;
  cpusPerTask?: number;
  memoryPerCpu?: string;
  memoryPerNode?: string;
  licenses?: string[];
  constraints?: string;
  exclusive?: boolean;
}
/**
 * This interface was referenced by `CustosWorkflow`'s JSON-Schema
 * via the `definition` "gpuRequest".
 */
export interface GpuRequest {
  type?: string;
  count: number;
}
/**
 * This interface was referenced by `CustosWorkflow`'s JSON-Schema
 * via the `definition` "image".
 */
export interface Image {
  uri: string;
}
/**
 * This interface was referenced by `CustosWorkflow`'s JSON-Schema
 * via the `definition` "multinode".
 */
export interface Multinode {
  nodes: number;
  implementation: "openmpi" | "mpich" | "generic";
  procsPerNode?: number;
}
/**
 * This interface was referenced by `CustosWorkflow`'s JSON-Schema
 * via the `definition` "softwareRequirement".
 */
export interface SoftwareRequirement {
  name: string;
  version: string;
}
/**
 * This interface was referenced by `CustosWorkflow`'s JSON-Schema
 * via the `definition` "output".
 */
export interface Output {
  type: "file";
  path: string;
}
/**
 * This interface was referenced by `CustosWorkflow`'s JSON-Schema
 * via the `definition` "retry".
 */
export interface Retry {
  attempts: number;
  on?: ("FAILED" | "NODE_FAIL" | "TIMEOUT")[];
}
/**
 * This interface was referenced by `CustosWorkflow`'s JSON-Schema
 * via the `definition` "arraySpec".
 */
export interface ArraySpec {
  start: number;
  end: number;
  step?: number;
  maxConcurrent?: number;
}
