// docsconfig regenerates docs/configuration.md from the config struct's
// yaml/doc tags plus config.Default() values.
package main

import (
	"fmt"
	"os"
	"reflect"
	"sort"
	"strings"
	"time"

	"github.com/Exonical/custos/internal/platform/config"
)

// preamble is a raw string; "@@" stands in for backticks, which raw
// string literals cannot contain.
const preamble = `# Configuration

Generated by tools/docsconfig — do not edit by hand.

## Sources and precedence

1. Built-in defaults (@@config.Default()@@).
2. YAML config file (@@--config@@ / @@CUSTOS_CONFIG@@), overlaid
   field-by-field.
3. Environment variables @@CUSTOS_<SECTION>__<KEY>@@ (@@__@@ separates
   nesting levels, keys uppercased). @@worker.kinds@@ maps cannot be set
   via env.

Secret fields (@@Secret@@ type) also accept @@<NAME>_FILE@@ pointing at a
file whose trimmed contents are the value; setting both the variable and
its @@_FILE@@ variant is an error. Secrets are never logged or serialized.

## Fail-closed rules

Validation aborts startup (@@config.invalid@@) when:

- @@server.tls.mode=required@@ (the default) without
  @@cert_file@@/@@key_file@@; @@mode=disabled@@ only with @@dev_mode@@.
- @@database.ssl_mode=disable@@ only with @@dev_mode@@; the URL must not
  contain @@sslmode@@/@@sslrootcert@@/@@sslcert@@/@@sslkey@@ (TLS is
  configured via @@database.ssl_mode@@, never the URL).
- @@telemetry.insecure@@ only with @@dev_mode@@.
- Without @@dev_mode@@: @@auth.oidc@@ issuer (https URL), client_id and
  at least one audience are required.
- CORS origins must be absolute https origins (http only in dev_mode);
  no @@*@@; @@server.trusted_proxies@@ must be CIDRs.

## Keys

| Key | Type | Default | Env | Description |
| --- | ---- | ------- | --- | ----------- |
`

type row struct {
	key, typ, def, env, doc string
}

func main() {
	var rows []row
	walk(reflect.TypeOf(config.Config{}), reflect.ValueOf(config.Default()), "", "CUSTOS", &rows)
	sort.Slice(rows, func(i, j int) bool { return rows[i].key < rows[j].key })

	var b strings.Builder
	b.WriteString(strings.ReplaceAll(preamble, "@@", "`"))
	cell := func(s string) string { return strings.ReplaceAll(s, "|", "\\|") }
	for _, r := range rows {
		fmt.Fprintf(&b, "| `%s` | %s | `%s` | `%s` | %s |\n",
			cell(r.key), cell(r.typ), cell(r.def), cell(r.env), cell(r.doc))
	}
	// Generated documentation, not sensitive: 0644 is intentional.
	if err := os.WriteFile("docs/configuration.md", []byte(b.String()), 0o644); err != nil { // #nosec G306
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}

func walk(t reflect.Type, v reflect.Value, prefix, envPrefix string, rows *[]row) {
	for i := 0; i < t.NumField(); i++ {
		f := t.Field(i)
		fv := v.Field(i)
		key := yamlName(f)
		if key == "-" {
			continue
		}
		full := key
		if prefix != "" {
			full = prefix + "." + key
		}
		env := envPrefix + "__" + strings.ToUpper(key)
		if envPrefix == "CUSTOS" {
			env = "CUSTOS_" + strings.ToUpper(key) // top level: single _
		}
		ft := f.Type
		if ft.Kind() == reflect.Pointer && ft.Elem().Kind() == reflect.Struct {
			*rows = append(*rows, row{full, "section", "", env, docTag(f)})
			ev := reflect.New(ft.Elem()).Elem()
			if !fv.IsNil() {
				ev = fv.Elem()
			}
			walk(ft.Elem(), ev, full, env, rows)
			continue
		}
		if ft.Kind() == reflect.Struct && ft != reflect.TypeOf(time.Duration(0)) {
			*rows = append(*rows, row{full, "section", "", env, docTag(f)})
			walk(ft, fv, full, env, rows)
			continue
		}
		if ft.Kind() == reflect.Map {
			*rows = append(*rows, row{full, "map<string,kind_limits>", "", env + " (unsupported)", docTag(f)})
			continue
		}
		*rows = append(*rows, row{full, typeName(ft), defString(fv), env, docTag(f)})
	}
}

func yamlName(f reflect.StructField) string {
	tag := f.Tag.Get("yaml")
	if i := strings.IndexByte(tag, ','); i >= 0 {
		tag = tag[:i]
	}
	return tag
}

func docTag(f reflect.StructField) string {
	d := f.Tag.Get("doc")
	if d == "" {
		return "(undocumented)"
	}
	return d
}

func typeName(t reflect.Type) string {
	if t == reflect.TypeOf(time.Duration(0)) {
		return "duration"
	}
	if t == reflect.TypeOf(config.Secret("")) {
		return "secret"
	}
	return t.Kind().String()
}

func defString(v reflect.Value) string {
	switch v.Kind() {
	case reflect.String:
		if v.Type() == reflect.TypeOf(config.Secret("")) {
			return "" // never print secret values
		}
		s := v.String()
		if s == "" {
			return ""
		}
		return s
	case reflect.Bool:
		return fmt.Sprintf("%v", v.Bool())
	case reflect.Int, reflect.Int32, reflect.Int64:
		if v.Type() == reflect.TypeOf(time.Duration(0)) {
			return v.Interface().(time.Duration).String()
		}
		return fmt.Sprintf("%d", v.Int())
	case reflect.Float64:
		return fmt.Sprintf("%g", v.Float())
	case reflect.Slice:
		if v.Len() == 0 {
			return ""
		}
		var parts []string
		for i := 0; i < v.Len(); i++ {
			parts = append(parts, fmt.Sprintf("%v", v.Index(i)))
		}
		return strings.Join(parts, ",")
	}
	return ""
}
